<?php

namespace Database\Seeders;

use App\Models\ChecklistItem;
use Illuminate\Database\Seeder;

class ChecklistPoin7Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // 01_Kurikulum (Root Folder Items)
            [
                'item_no' => 1,
                'code' => '01',
                'root_folder' => '01_Kurikulum',
                'subfolder' => '(root folder)',
                'document_name' => 'Kurikulum yang dipakai saat ini',
                'iso_clause' => '8.3.4.2; 8.3.4.3',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => 'Versi yang disahkan dan berlaku.',
                'is_per_course' => false,
                'sort_order' => 1,
            ],
            [
                'item_no' => 2,
                'code' => '01',
                'root_folder' => '01_Kurikulum',
                'subfolder' => '(root folder)',
                'document_name' => 'SK Pembentukan Tim Kurikulum',
                'iso_clause' => '8.3.2 e',
                'executor' => 'Fakultas & Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 2,
            ],
            [
                'item_no' => 3,
                'code' => '01',
                'root_folder' => '01_Kurikulum',
                'subfolder' => '(root folder)',
                'document_name' => 'Notulen meeting review/perubahan kurikulum (jika ada perubahan atau review)',
                'iso_clause' => '8.3.4.1; 8.3.6',
                'executor' => 'Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => 'Sertakan daftar hadir.',
                'is_per_course' => false,
                'sort_order' => 3,
            ],

            // 01_Kurikulum (Perangkat-Perkuliahan Items, Per Mata Kuliah)
            [
                'item_no' => 4,
                'code' => '01a',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/a_Silabus',
                'document_name' => 'Silabus',
                'iso_clause' => '8.3.4.3',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => 'Satu subfolder per MK semester Genap 2025/2026.',
                'is_per_course' => true,
                'sort_order' => 4,
            ],
            [
                'item_no' => 5,
                'code' => '01b',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/b_RencanaPembelajaran',
                'document_name' => 'Rencana pembelajaran (RPS)',
                'iso_clause' => '8.3.4.3; 8.1.2',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => 'Yang sudah disahkan.',
                'is_per_course' => true,
                'sort_order' => 5,
            ],
            [
                'item_no' => 6,
                'code' => '01c',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/c_Daftar-HadirPerkuliahan',
                'document_name' => 'Daftar hadir perkuliahan',
                'iso_clause' => '8.5.1.1 c; 8.5.2 a',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => 'Ekspor dari SIAKAD/LMS diperbolehkan.',
                'is_per_course' => true,
                'sort_order' => 6,
            ],
            [
                'item_no' => 7,
                'code' => '01d',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/d_JurnalPembelajaran',
                'document_name' => 'Jurnal pembelajaran',
                'iso_clause' => '8.5.2 c',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => null,
                'is_per_course' => true,
                'sort_order' => 7,
            ],
            [
                'item_no' => 8,
                'code' => '01e',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/e_Kontrak-Belajar',
                'document_name' => 'Kontrak belajar',
                'iso_clause' => '8.2.2',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => null,
                'is_per_course' => true,
                'sort_order' => 8,
            ],
            [
                'item_no' => 9,
                'code' => '01f',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/f_MateriPembelajaran',
                'document_name' => 'Materi pembelajaran',
                'iso_clause' => '7.1.6.2',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => null,
                'is_per_course' => true,
                'sort_order' => 9,
            ],
            [
                'item_no' => 10,
                'code' => '01g',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/g_Soal-UTS-UASdan-Verifikasi',
                'document_name' => 'Soal ujian UTS maupun UAS dan verifikasi soal ujiannya',
                'iso_clause' => '8.3.4.4; 8.3.4.1 c',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => 'Soal + form verifikasi per MK.',
                'is_per_course' => true,
                'sort_order' => 10,
            ],
            [
                'item_no' => 11,
                'code' => '01h',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/h_PedomanPraktikum',
                'document_name' => 'Pedoman praktikum (jika mata kuliah berkaitan dengan praktikum)',
                'iso_clause' => '8.5.1.3',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => "Pilih 'Tidak berlaku' jika tidak ada MK praktikum.",
                'is_per_course' => true,
                'sort_order' => 11,
            ],
            [
                'item_no' => 12,
                'code' => '01i',
                'root_folder' => '01_Kurikulum',
                'subfolder' => 'Perangkat-Perkuliahan/i_Bukti-Penilaian',
                'document_name' => 'Bukti penilaian pembelajaran (UTS, UAS, praktikum, tugas, dll.)',
                'iso_clause' => '8.5.1.4 b–c',
                'executor' => 'Dosen-dosen masing-masing pengampu mata kuliah',
                'level' => 'Prodi',
                'instructions' => 'Sampel lembar jawaban/tugas + rekap nilai per MK.',
                'is_per_course' => true,
                'sort_order' => 12,
            ],

            // 02_Skripsi
            [
                'item_no' => 13,
                'code' => '02a',
                'root_folder' => '02_Skripsi',
                'subfolder' => 'a_SK-Pembimbing-dan-Penguji',
                'document_name' => 'Surat penunjukan dosen pembimbing dan dosen penguji',
                'iso_clause' => '8.5.1.1 e',
                'executor' => 'Fakultas & Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 13,
            ],
            [
                'item_no' => 14,
                'code' => '02b',
                'root_folder' => '02_Skripsi',
                'subfolder' => 'b_Buku-Panduan-Skripsi',
                'document_name' => 'Buku panduan skripsi',
                'iso_clause' => '8.2.2; 7.5.2',
                'executor' => 'Prodi',
                'level' => 'Fakultas',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 14,
            ],
            [
                'item_no' => 15,
                'code' => '02c',
                'root_folder' => '02_Skripsi',
                'subfolder' => 'c_Bukti-Bimbingan',
                'document_name' => 'Bukti hasil bimbingan skripsi',
                'iso_clause' => '8.5.2 a & c',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 15,
            ],
            [
                'item_no' => 16,
                'code' => '02d',
                'root_folder' => '02_Skripsi',
                'subfolder' => 'd_Bukti-Cek-Plagiasi',
                'document_name' => 'Bukti pengecekan plagiasi untuk judul skripsi yang sudah diujikan',
                'iso_clause' => '8.5.1.4 a',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => 'Untuk skripsi yang diujikan semester terakhir.',
                'is_per_course' => false,
                'sort_order' => 16,
            ],
            [
                'item_no' => 17,
                'code' => '02e',
                'root_folder' => '02_Skripsi',
                'subfolder' => 'e_Kebijakan-Plagiasi',
                'document_name' => 'Kebijakan plagiasi (toleransi persentase plagiasi)',
                'iso_clause' => '8.5.1.4 a; B.10',
                'executor' => 'Fakultas',
                'level' => 'Fakultas',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 17,
            ],
            [
                'item_no' => 18,
                'code' => '02f',
                'root_folder' => '02_Skripsi',
                'subfolder' => 'f_Penilaian-Sidang',
                'document_name' => 'Bukti penilaian hasil sidang skripsi',
                'iso_clause' => '8.5.1.5 e',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 18,
            ],
            [
                'item_no' => 19,
                'code' => '02g',
                'root_folder' => '02_Skripsi',
                'subfolder' => 'g_Bukti-Persyaratan-Sidang',
                'document_name' => 'Bukti pemenuhan persyaratan untuk mengikuti sidang skripsi',
                'iso_clause' => '8.2.2 g; 8.6',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 19,
            ],

            // 03_Wisuda
            [
                'item_no' => 20,
                'code' => '03a',
                'root_folder' => '03_Wisuda',
                'subfolder' => 'a_Bukti-Persyaratan-Wisuda',
                'document_name' => 'Bukti pemenuhan persyaratan wisuda',
                'iso_clause' => '8.6',
                'executor' => 'Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 20,
            ],
            [
                'item_no' => 21,
                'code' => '03b',
                'root_folder' => '03_Wisuda',
                'subfolder' => 'b_Pelaporan-Kelulusan-PDDIKTI',
                'document_name' => 'Bukti penyampaian mahasiswa yang sudah dinyatakan lulus ke PDDIKTI',
                'iso_clause' => '8.5.2 a',
                'executor' => 'Prodi, minta ke SIPD',
                'level' => 'Fakultas & Prodi',
                'instructions' => 'Tangkapan layar atau laporan operator PDDIKTI.',
                'is_per_course' => false,
                'sort_order' => 21,
            ],
            [
                'item_no' => 22,
                'code' => '03c',
                'root_folder' => '03_Wisuda',
                'subfolder' => 'c_Transkrip-dan-Ijazah',
                'document_name' => 'Transkrip nilai dan ijazah',
                'iso_clause' => '8.5.1.5 d; 8.5.3',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => 'Cukup sampel.',
                'is_per_course' => false,
                'sort_order' => 22,
            ],

            // 04_Evaluasi-dan-Akreditasi
            [
                'item_no' => 23,
                'code' => '04a',
                'root_folder' => '04_Evaluasi-dan-Akreditasi',
                'subfolder' => 'a_Sertifikat-Akreditasi-BAN-PT-LAM',
                'document_name' => 'Sertifikat akreditasi BAN-PT / LAM PT',
                'iso_clause' => 'Lampiran E',
                'executor' => 'Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => 'Fakultas menyimpan rekap akreditasi kedua prodi.',
                'is_per_course' => false,
                'sort_order' => 23,
            ],
            [
                'item_no' => 24,
                'code' => '04b',
                'root_folder' => '04_Evaluasi-dan-Akreditasi',
                'subfolder' => 'b_Survei-Kepuasan-Interested-Parties',
                'document_name' => 'Bukti dan analisis survei kepuasan interested parties',
                'iso_clause' => '9.1.2.1; 9.1.5',
                'executor' => 'UJM',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 24,
            ],
            [
                'item_no' => 25,
                'code' => '04c',
                'root_folder' => '04_Evaluasi-dan-Akreditasi',
                'subfolder' => 'c_Tracer-Study',
                'document_name' => 'Bukti tracer study beserta analisis, monitoring, dan evaluasinya',
                'iso_clause' => '8.5.2 b; 9.1.3',
                'executor' => 'Tracer Study',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 25,
            ],
            [
                'item_no' => 26,
                'code' => '04d',
                'root_folder' => '04_Evaluasi-dan-Akreditasi',
                'subfolder' => 'd_EDOM-Semester-Genap-Terakhir',
                'document_name' => 'Hasil EDOM terakhir untuk perkuliahan semester genap',
                'iso_clause' => '9.1.2.1; 7.2.1',
                'executor' => 'UJM/KPM',
                'level' => 'Fakultas & Prodi',
                'instructions' => 'Semester Genap 2025/2026.',
                'is_per_course' => false,
                'sort_order' => 26,
            ],
            [
                'item_no' => 27,
                'code' => '04e',
                'root_folder' => '04_Evaluasi-dan-Akreditasi',
                'subfolder' => 'e_Dokumen-Evaluasi-Diri',
                'document_name' => 'Dokumen evaluasi diri terakhir',
                'iso_clause' => '4.1; 9.1.5',
                'executor' => 'Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 27,
            ],
            [
                'item_no' => 28,
                'code' => '04f',
                'root_folder' => '04_Evaluasi-dan-Akreditasi',
                'subfolder' => 'f_Laporan-Kinerja-Program-Studi',
                'document_name' => 'Laporan kinerja program studi',
                'iso_clause' => '9.1.4; Lampiran E',
                'executor' => 'Prodi',
                'level' => 'Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 28,
            ],

            // 05_Penelitian-dan-PkM
            [
                'item_no' => 29,
                'code' => '05a',
                'root_folder' => '05_Penelitian-dan-PkM',
                'subfolder' => 'a_Blueprint-Penelitian-dan-PkM',
                'document_name' => 'Blueprint penelitian dan pengabdian kepada masyarakat',
                'iso_clause' => '6.2',
                'executor' => 'Dosen & Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 29,
            ],
            [
                'item_no' => 30,
                'code' => '05b',
                'root_folder' => '05_Penelitian-dan-PkM',
                'subfolder' => 'b_Proposal-Hibah-Publikasi-dan-CekPlagiasi',
                'document_name' => 'Proposal hibah penelitian dan pengabdian termasuk publikasi, beserta cek plagiasinya',
                'iso_clause' => 'Lampiran E; B.10',
                'executor' => 'Dosen & Prodi',
                'level' => 'Fakultas & Prodi',
                'instructions' => null,
                'is_per_course' => false,
                'sort_order' => 30,
            ],
        ];

        foreach ($items as $item) {
            ChecklistItem::updateOrCreate(
                ['item_no' => $item['item_no']],
                $item
            );
        }
    }
}
